config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root to: 'articles#index'
  get 'archives', to: 'articles#archives'

  resources :articles do
    resources :comments, only: [:new, :create, :edit, :update, :destroy]
    resource :likes, only: [:show, :create]
  end

  resources :ranks, only: [:index]
  resource :profile, only: [:show, :edit, :update]
  resources :users, only: [:show]
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id           :integer          not null, primary key
#  introduction :text
#  nickname     :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  user_id      :integer          not null
#
# Indexes
#
#  index_profiles_on_user_id  (user_id)
#
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar

  validates :nickname, presence: true
  validates :introduction, presence: true
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]

  def show
    @profile = current_user.profile
  end

  def edit
    @profile = current_user.prepare_profile
  end

  def update
    @profile = current_user.prepare_profile
    @profile.assign_attributes(profile_params)

    if @profile.save
      flash[:success] = 'プロフィールを作成したよ！いいね！'
      redirect_to profile_path
    else
      render :edit
    end
  end

  private

    def profile_params
      params.require(:profile).permit(
        :nickname,
        :introduction,
        :avatar
      )
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.haml
.outer.container
  .row
    = form_with(model: @profile, url: profile_path, method: 'put', local: true) do |f|
      %ul.mt-3
        - @profile.errors.full_messages.each do |message|
          %li= message
      .form-signin
        .mb-4
          = f.label :avatar, 'アイコン'
          = f.file_field :avatar
        .mb-3
          = f.label :nickname, 'ニックネーム（表示名）', class: 'form-label'
          = f.text_field :nickname, class: 'form-control'
        .mb-3
          = f.label :introduction, '自己紹介'
          = f.text_area :introduction, class: 'form-control rich-text-area'
        = f.submit '送信する', class: "btn-blue-bc"

app/views/profiles/show.html.haml
%main.articles
  .outer.container
    .row.profile-container
      .col-2.profile-images
        = image_tag current_user.avatar_image
      .col-10.profile-wrapper
        .profile-header
          .profile-info
            %p.profile-name
              = current_user.display_nickname
            .profile-edit-btn
              = link_to '編集', edit_profile_path
        %p.profile-introduction
          = current_user.profile&.introduction

    %ul.profile-article
      - current_user.articles.each do |article|
        .card.is-active.profile-card.col-4.mb-3
          = link_to article_path(article) do
            .card-body
              %h3.card-title= article.title.truncate(20)
              %p.card-text!= article.content
              .link-btn-wrapper
                .like-btn
                  - if article.likes_count == 0
                    = image_tag 'heart.svg', class: 'like-button-img'
                  - else
                    = image_tag 'heart-active.svg', class: 'like-button-img'
                %span{id: "article-likes-#{article.id}"}= article.likes_count
              %p.card-time-text= "#{time_ago_in_words(article.created_at)}前"
            .card-footer
              .card-footer-left
                %p= nickname_or_name(article)
                = image_tag current_user.avatar_image, alt: 'アイコン', class: 'avatar'