config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root to: 'articles#index'
  get 'archives', to: 'articles#archives'

  resources :articles do
    resources :comments, only: [:new, :create, :edit, :update, :destroy]
    resource :likes, only: [:show, :create]
  end

  resources :ranks, only: [:index]
  resource :profile, only: [:show, :edit, :update]
  resources :users, only: [:show]
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id          :integer          not null, primary key
#  likes_count :integer          default(0)
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  bot_id      :integer          default(0)
#  user_id     :integer          not null
#
# Indexes
#
#  index_articles_on_user_id                 (user_id)
#  index_articles_on_user_id_and_created_at  (user_id,created_at)
#
# Foreign Keys
#
#  user_id  (user_id => users.id)
#
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_rich_text :content
  has_many :likes, dependent: :destroy
  has_many :bots

  validates :user_id, presence: true
  validates :title,   presence: true, length: {maximum: 100}
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_articles, only: [:index, :show, :archives]
  before_action :authenticate_user!, only: [:new, :create, :update, :destroy]

  def index
    @article  = @articles.first
    if @article
      @comments = @article.comments
      @comment  = Comment.new
      @likes = @article.likes_count
    end
  end

  def show
    @article  = @articles.find(params[:id])
    @comments = @article.comments
    @comment = Comment.new
    @likes = @article.likes_count
    render :index
  end

  def new
    @article  = current_user.articles.build
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      flash[:success] = 'よし！目標を作成できた！頑張ろう！'
      redirect_to root_url
    else
      render :new
    end
  end

  def edit
    @article = current_user.articles.find(params[:id])
  end

  def update
    @article = current_user.articles.find(params[:id])
    if @article.update(article_params)
      flash[:success] = 'いいね！目標を改善した！頑張れる気がする！'
      redirect_to root_url
    else
      render :edit
    end
  end

  def destroy
    current_user.articles.find(params[:id]).destroy
    flash[:success] = '削除してしまった、、次頑張ろう！'
    redirect_to root_url
  end

  def archives
    @articles = Article.all.order(updated_at: :desc).paginate(page: params[:page])
  end

  private

    def article_params
      params.require(:article).permit(:title, :content)
    end

    def set_articles
      @articles = Article.all.order(updated_at: :desc).paginate(page: params[:page])
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def user_name(article)
    User.find_by(id: article.user_id).name
  end

  def user_nickname(article)
    User.find_by(id: article.user_id).profile&.nickname
  end

  def nickname_or_name(article)
    user_nickname(article) || user_name(article)
  end

  def bot_name(article)
    bot = Bot.find_by(id: article.bot_id)
    bot&.bot_name
  end
end

app/views/articles/_form.html.haml
.outer.container
  .row
    = form_with(model: @article, local: true) do |f|
      %ul
        - @article.errors.full_messages.each do |message|
          %li= message
      .form-signin
        .mb-3
          = f.label :タイトル, class: 'form-label'
          = f.text_field :title, class: 'form-control'
        .mb-3
          = f.label :内容
          != f.rich_text_area :content, class: 'form-control rich-text-area'
        = f.submit '送信する', class: "btn-blue-bc"

app/views/articles/archives.html.haml
- if @articles
  .conteiner.articles.outer
    %h1.archives-heading みんなの目標一覧
    = will_paginate
    %ul.row
      - @articles.each do |article|
        %li.card.mb-3.is-active
          = link_to article_path(article) do
            .card-body
              %h3.card-title= article.title.truncate(20)
              %p.card-text!= article.content
              .link-btn-wrapper
                .like-btn
                  - if article.likes_count == 0
                    = image_tag 'heart.svg', class: 'like-button-img'
                  - else
                    = image_tag 'heart-active.svg', class: 'like-button-img'
                %span= article.likes_count
            %p.card-time-text= "#{time_ago_in_words(article.created_at)}前"
          .card-footer
            .card-footer-left
              %p= nickname_or_name(article)
              = link_to user_path(article.user_id) do
                = image_tag article.user.avatar_image, alt: 'アイコン', class: 'avatar'
    = will_paginate

app/views/articles/edit.html.haml
= render 'form'

app/views/articles/index.html.haml
%main.articles
  .outer.container
    .row
      %ul.home-left.col-4
        = render 'shared/articles'
        = link_to 'もっと見る', archives_path, class: 'more-btn'
      .home-right.col-8
        = render 'shared/article'
        = render 'shared/comment'
        .comments-container
        - if user_signed_in? && @article
          = form_with(model: @comment, url: article_comments_path(@article.id), local: true) do |f|
            - @comment.errors.full_messages.each do |message|
              %li= message
            .form-signin
              .mb-3
                = f.hidden_field :user_id, :value => current_user.id
                = f.hidden_field :article_id, :value => @article.id
                = f.text_area :content, class: 'form-control', required: true
              = f.submit '応援する', class: "btn-blue-bc add-comment-button"

= javascript_pack_tag 'like'

app/views/articles/new.html.haml
= render 'form'