config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root to: 'articles#index'
  get 'archives', to: 'articles#archives'

  resources :articles do
    resources :comments, only: [:new, :create, :edit, :update, :destroy]
    resource :likes, only: [:show, :create]
  end

  resources :ranks, only: [:index]
  resource :profile, only: [:show, :edit, :update]
  resources :users, only: [:show]
end

app/views/shared/_article.html.haml
- if @article
  %li.card.mb-3#article-id{data: {article_id: @article.id}}
    .card-body
      %h3.card-title= @article.title
      %p.card-text!= @article.content
      .link-btn-wrapper
        .bubbly-button.create-like-btn
          - if @article.likes_count == 0
            = image_tag 'heart.svg', class: 'like-button-img'
          - else
            = image_tag 'heart-active.svg', class: 'like-button-img'
        %span{id: "likes-#{@article.id}"}= @likes
      %p.card-time-text= "#{time_ago_in_words(@article.created_at)}前"
    .card-footer
      .card-footer-left
        %p= nickname_or_name(@article)
        = link_to user_path(@article.user_id) do
          = image_tag @article.user.avatar_image, alt: 'アイコン', class: 'avatar'
      - if user_signed_in? && current_user.articles.exists?(id: @article.id)
        .card-footer-right
          = link_to edit_article_path(@article) do
            = image_tag 'edit-icon.png', alt: '編集ボタン', class: 'edit'
          %div{"data-micromodal-trigger" => "modal-#{@article.id}"}
            = image_tag 'delete-icon.png', alt: '削除ボタン', class: 'delete'
    = render 'shared/modal', article: @article

= javascript_pack_tag 'micromodal'
:javascript
  var animateButton = function(e) {
    e.preventDefault;
    e.target.classList.remove('animate');

    e.target.classList.add('animate');
    setTimeout(function(){
      e.target.classList.remove('animate');
    },700);
  };

  var bubblyButtons = document.getElementsByClassName("bubbly-button");
  for (var i = 0; i < bubblyButtons.length; i++) {
    bubblyButtons[i].addEventListener('click', animateButton, false);
  }

app/views/shared/_articles.html.haml
- if @article
  - @articles.first(10).each do |article|
    %li.card.mb-3.is-active
      = link_to article_path(article) do
        .card-body
          %h3.card-title= article.title.truncate(20)
          %p.card-text!= article.content
          .link-btn-wrapper
            .like-btn
              - if article.likes_count == 0
                = image_tag 'heart.svg', class: 'like-button-img'
              - else
                = image_tag 'heart-active.svg', class: 'like-button-img'
            %span{id: "article-likes-#{article.id}"}= article.likes_count
          %p.card-time-text= "#{time_ago_in_words(article.created_at)}前"
      .card-footer
        .card-footer-left
          %p= nickname_or_name(article) 
          = link_to user_path(@article.user_id) do
            = image_tag article.user.avatar_image, alt: 'アイコン', class: 'avatar'

app/views/shared/_comment.html.haml
%ul
  - if @article
    - @comments.each do |comment|
      %li.card.mb-3.comment-card
        .card-body
          %p.card-text.comment-text= comment.content
        .card-footer
          .card-footer-left
            %p= bot_or_user_name(comment)
            - if comment.bot_id.zero?
              = link_to user_path(comment.user_id) do
                = image_tag comment.user.avatar_image, alt: 'アバター画像', class: 'avatar'
            - else
              = image_tag comment.img, alt: 'アバター画像', class: 'avatar'
          - if login_and_commented_user?(comment)

            .card-footer-right
              .comment-edit-wrap.show-comment-form
                = image_tag 'edit-icon.png',   alt: '編集ボタン', class: 'edit'
              = link_to article_comment_path(comment.article_id, comment.id), data: { method: 'delete', confirm: "削除するの?" } do
                = image_tag 'delete-icon.png', alt: '削除ボタン', class: 'delete'
        .comment-text-area
          - if user_signed_in?
            = form_with(model: comment, url: article_comment_path(@article.id, comment.id), local: true) do |f|
              - comment.errors.full_messages.each do |message|
                %li= message
              .form-edit-comment
                %div
                  = f.hidden_field :user_id, :value => current_user.id
                  = f.hidden_field :article_id, :value => @article.id
                  = f.text_area :content, class: 'form-control', required: true
                = f.submit '編集する', class: "btn-blue-bc"

app/views/shared/_modal.html.haml
.modal.micromodal-slide{id: "modal-#{article.id}", "aria-hidden" => "true"}
  .modal__overlay{"data-micromodal-close" => "", :tabindex => "-1"}
    .modal__container{"aria-labelledby" => "modal-1-title", "aria-modal" => "true", :role => "dialog"}
      %header.modal__header
        = image_tag 'delete-eva.jpeg'
      %main#modal-1-content.modal__content
      .modal__footer
        = link_to '逃げる', article_path(article), data: {method: 'delete', confirm: '削除しますか？'}, class: 'modal__btn modal__btn-primary'
        %button.modal__btn{"aria-label" => "Close this dialog window", "data-micromodal-close" => ""} 逃げない